"""Message & ToolCall models — the atoms of ReAct state."""

from __future__ import annotations

import json
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class MessageRole(str, Enum):
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"


class ToolCall(BaseModel):
    """A request from the LLM to invoke a tool."""

    id: str  # tool_call_id, globally unique within a thread
    name: str
    arguments: dict[str, Any] = Field(default_factory=dict)
    # Generated by Loop, NOT by LLM. Used for idempotent re-execution.
    idempotency_key: str | None = None


class ToolResult(BaseModel):
    """The outcome of a tool execution. Sent back to the LLM as a tool message."""

    tool_call_id: str
    name: str
    content: str
    is_error: bool = False
    idempotency_key: str | None = None


class Message(BaseModel):
    """One entry in the ReAct message history."""

    role: MessageRole
    content: str = ""
    # For assistant messages that requested tools.
    tool_calls: list[ToolCall] = Field(default_factory=list)
    # For tool messages: which tool_call_id this answers.
    tool_call_id: str | None = None
    # Free-form metadata (e.g. compressed=true, summary_of=N earlier turns).
    meta: dict[str, Any] = Field(default_factory=dict)

    def to_openai_dict(self) -> dict[str, Any]:
        """Render as an OpenAI chat-completions message.

        This is the wire format DeepSeek and OpenAI both accept. Getting it
        wrong is not a cosmetic problem: the API rejects the whole request
        with a 422 naming the offending index, e.g.

            messages[4]: missing field `type`

        Two details are easy to get wrong and both are load-bearing:

        1. Every entry in `tool_calls` needs `{"type": "function",
           "function": {"name": ..., "arguments": ...}}` — the name and
           arguments are nested one level deeper than they look, and `type`
           is mandatory.
        2. `function.arguments` is a **JSON-encoded string**, not an object.
           Passing a dict makes the API reject the request.
        """
        if self.role == MessageRole.TOOL:
            return {
                "role": "tool",
                "content": self.content,
                "tool_call_id": self.tool_call_id,
            }
        if self.tool_calls:
            return {
                "role": "assistant",
                # Some providers reject a literal null here; empty string is
                # universally accepted for a tool-call-only turn.
                "content": self.content or "",
                "tool_calls": [
                    {
                        "id": tc.id,
                        "type": "function",
                        "function": {
                            "name": tc.name,
                            "arguments": json.dumps(
                                tc.arguments, ensure_ascii=False
                            ),
                        },
                    }
                    for tc in self.tool_calls
                ],
            }
        return {"role": self.role.value, "content": self.content}


def _unanswered_reply(tc: ToolCall) -> Message:
    return Message(
        role=MessageRole.TOOL,
        content=(
            "error: no result was recorded for this call — it never ran. "
            "Do not assume it succeeded."
        ),
        tool_call_id=tc.id,
        meta={"tool_name": tc.name, "sealed": True, "is_error": True},
    )


def repair_tool_call_ordering(
    messages: list[Message],
) -> tuple[list[Message], list[str]]:
    """Return a copy of `messages` that satisfies the provider ordering rule.

    Two ways a history can be malformed, and both are hard 400s:

    * an assistant message carrying tool_calls with no tool replies directly
      after it, and
    * a tool message whose call was never made, or whose call has already been
      answered — an orphan.

    The second is what a naive repair creates. Appending the missing replies to
    the end of the list looks like it fixes things, but the provider requires
    them *adjacent* to the call, so anything that arrived after the assistant
    message (a user turn, say) still sits in between and the request is still
    rejected. This rebuilds the list instead, inserting each reply directly
    after its call and dropping replies that have nowhere to belong.

    Returns (repaired, notes) where notes describes what changed, so callers
    can log it rather than repairing silently.
    """
    repaired: list[Message] = []
    notes: list[str] = []
    i = 0
    while i < len(messages):
        m = messages[i]
        if m.role == MessageRole.ASSISTANT and m.tool_calls:
            repaired.append(m)
            replied: dict[str, Message] = {}
            j = i + 1
            while j < len(messages) and messages[j].role == MessageRole.TOOL:
                if messages[j].tool_call_id:
                    replied.setdefault(messages[j].tool_call_id, messages[j])
                j += 1
            for tc in m.tool_calls:
                if tc.id in replied:
                    repaired.append(replied[tc.id])
                else:
                    notes.append(f"filled:{tc.id}")
                    repaired.append(_unanswered_reply(tc))
            i = j
            continue
        if m.role == MessageRole.TOOL:
            notes.append(f"dropped_orphan:{m.tool_call_id}")
            i += 1
            continue
        repaired.append(m)
        i += 1
    return repaired, notes


def unanswered_tool_calls(messages: list[Message]) -> list[ToolCall]:
    """Tool calls in the last assistant turn that never received a reply.

    OpenAI-compatible endpoints require an assistant message carrying
    tool_calls to be followed immediately by one tool message per
    tool_call_id. A history that ends on an unanswered call is not merely
    untidy — replaying it is a hard 400:

        An assistant message with 'tool_calls' must be followed by tool
        messages responding to each 'tool_call_id'.

    It is also easy to produce by accident, which is why this lives here
    rather than being open-coded at each call site: a rejected approval leaves
    the call hanging, and so does sending a new message to a thread that is
    still parked.
    """
    for i in range(len(messages) - 1, -1, -1):
        m = messages[i]
        if m.role != MessageRole.ASSISTANT or not m.tool_calls:
            continue
        answered = {
            later.tool_call_id
            for later in messages[i + 1 :]
            if later.role == MessageRole.TOOL
        }
        return [tc for tc in m.tool_calls if tc.id not in answered]
    return []
